apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: grpc-k8s-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-grpck8scient
  template:
    metadata:
      labels:
        app: svc-grpck8scient
    spec:
      containers:
        - name: grpc-k8s-client
          image: weikebala/grpc_k8s_client
          imagePullPolicy: IfNotPresent