apiVersion: v1
kind: Service
metadata:
  name: grpcK8sServer
  labels:
    app: svc-grpck8sserver
spec:
  ports:
    - port: 8028
      targetPort:8028
      protocol: TCP
  selector:
    app: svc-grpck8sserver
---
apiVersion: v1
kind: Deployment
metadata:
  namespace: default
  name: grpcK8sServer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-grpck8sserver
  template:
    metadata:
      labels:
        app: svc-grpck8sserver
    spec:
      containers:
        - name: grpc_k8s_server
          image: weikebala/grpc_k8s_server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8028
              name: server-rpc